## Homework

Import libraries

In [361]:
import numpy as np
import pandas as pd

Q1: Numpy version

In [362]:
np.__version__

'1.21.5'

Q2: How many records in dataset?

In [363]:
df = pd.read_csv('data.csv')
df.index

RangeIndex(start=0, stop=11914, step=1)

In [364]:
len(df.index)

11914

Q3: What are the top-3 most popular manufacturers?

In [365]:
df.head(n=4)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450

In [366]:
make_count = df.groupby('Make').Make.count()
make_count

Make
Acura             252
Alfa Romeo          5
Aston Martin       93
Audi              328
BMW               334
Bentley            74
Bugatti             3
Buick             196
Cadillac          397
Chevrolet        1123
Chrysler          187
Dodge             626
FIAT               62
Ferrari            69
Ford              881
GMC               515
Genesis             3
HUMMER             17
Honda             449
Hyundai           303
Infiniti          330
Kia               231
Lamborghini        52
Land Rover        143
Lexus             202
Lincoln           164
Lotus              29
Maserati           58
Maybach            16
Mazda             423
McLaren             5
Mercedes-Benz     353
Mitsubishi        213
Nissan            558
Oldsmobile        150
Plymouth           82
Pontiac           186
Porsche           136
Rolls-Royce        31
Saab              111
Scion              60
Spyker              3
Subaru            256
Suzuki            351
Tesla              18
Toyot

In [367]:
make_count.sort_values(ascending=False).head(3)

Make
Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Q4: Number of unique Audi car models

In [368]:
df[df.Make.str.lower()=='audi'].Model.unique()

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [369]:
len(df[df.Make.str.lower()=='audi'].Model.unique())

34

Q5: Number of columns with missing values

In [370]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [371]:
nulls_df = df.isnull().sum().to_frame('Nulls')
nulls_df

Nulls
Make                   0
Model                  0
Year                   0
Engine Fuel Type       3
Engine HP             69
Engine Cylinders      30
Transmission Type      0
Driven_Wheels          0
Number of Doors        6
Market Category     3742
Vehicle Size           0
Vehicle Style          0
highway MPG            0
city mpg               0
Popularity             0
MSRP                   0

In [372]:
nulls_df.index

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [373]:
nulls_df[nulls_df.Nulls>0]

Nulls
Engine Fuel Type      3
Engine HP            69
Engine Cylinders     30
Number of Doors       6
Market Category    3742

In [374]:
(df.isnull().sum()>0).sum()

5

Q6: Does the median value change after filling missing values?


In [375]:
column_to_test = 'Engine Cylinders'

# asserting that some rows have missing Engine Cylinders
assert len(df[df[column_to_test].isnull()])>0

# showing a sample of empty Engine Cylinders
df[df[column_to_test].isnull()].head(3)

Make    Model  Year Engine Fuel Type  Engine HP  Engine Cylinders  \
1983   Chevrolet  Bolt EV  2017         electric      200.0               NaN   
1984   Chevrolet  Bolt EV  2017         electric      200.0               NaN   
3716  Volkswagen   e-Golf  2015         electric      115.0               NaN   

     Transmission Type      Driven_Wheels  Number of Doors Market Category  \
1983      DIRECT_DRIVE  front wheel drive              4.0       Hatchback   
1984      DIRECT_DRIVE  front wheel drive              4.0       Hatchback   
3716      DIRECT_DRIVE  front wheel drive              4.0       Hatchback   

     Vehicle Size  Vehicle Style  highway MPG  city mpg  Popularity   MSRP  
1983      Compact  4dr Hatchback          110       128        1385  40905  
1984      Compact  4dr Hatchback          110       128        1385  36620  
3716      Compact  4dr Hatchback          105       126         873  33450

In [376]:
# Computing the median
median_before_replacement = df[column_to_test].median()
median_before_replacement

6.0

In [377]:
# computing the mode
df[column_to_test].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [378]:
# struct to replace the missing values
value={column_to_test: df[column_to_test].mode()[0]}
value

{'Engine Cylinders': 4.0}

In [379]:
# replacing missing values and asserting that everything has been replaced properly
df.fillna(value=value, inplace=True)
assert len(df[df[column_to_test].isnull()])==0

In [380]:
# computing the median again
median_after_replacement = df[column_to_test].median()
median_after_replacement


6.0

In [381]:
# has the value of the median changed?
median_after_replacement != median_before_replacement

False

Q7: Value of the first element of w

In [382]:
X = df[df.Make == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates().to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [383]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [384]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [385]:
XTX_inv.dot(XTX)

array([[ 1.00000000e+00,  6.76542156e-17],
       [-1.47104551e-14,  1.00000000e+00]])

In [386]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [387]:
w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

In [388]:
w[0]

4.5949448100945744